// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgFLm12aKI4EkZ8TLx94NpzjvoNHiPh4',
    appId: '1:134147853973:web:11f46fd1614cf98eff559c',
    messagingSenderId: '134147853973',
    projectId: 'feiragreen-3d1ed',
    authDomain: 'feiragreen-3d1ed.firebaseapp.com',
    storageBucket: 'feiragreen-3d1ed.firebasestorage.app',
    measurementId: 'G-HLFE8126RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbx-FGBrNf4tshyAgtzjXEF_DoSidU63o',
    appId: '1:134147853973:android:07c41cd51cf6abddff559c',
    messagingSenderId: '134147853973',
    projectId: 'feiragreen-3d1ed',
    storageBucket: 'feiragreen-3d1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAD5Be_dl6SzODoTWIGKe_k6pZBzSgRcI',
    appId: '1:134147853973:ios:ce77d4d412f585a2ff559c',
    messagingSenderId: '134147853973',
    projectId: 'feiragreen-3d1ed',
    storageBucket: 'feiragreen-3d1ed.firebasestorage.app',
    iosBundleId: 'com.example.meuProjetoIntegrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAD5Be_dl6SzODoTWIGKe_k6pZBzSgRcI',
    appId: '1:134147853973:ios:ce77d4d412f585a2ff559c',
    messagingSenderId: '134147853973',
    projectId: 'feiragreen-3d1ed',
    storageBucket: 'feiragreen-3d1ed.firebasestorage.app',
    iosBundleId: 'com.example.meuProjetoIntegrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmgFLm12aKI4EkZ8TLx94NpzjvoNHiPh4',
    appId: '1:134147853973:web:1b223f2d5bce751fff559c',
    messagingSenderId: '134147853973',
    projectId: 'feiragreen-3d1ed',
    authDomain: 'feiragreen-3d1ed.firebaseapp.com',
    storageBucket: 'feiragreen-3d1ed.firebasestorage.app',
    measurementId: 'G-0F5VG574DW',
  );
}
